name = "climbinsight"
compatibility_date = "2024-04-06"

[build]
command = "npm run pages:build"

[site]
bucket = ".vercel/output/static"

[[routes]]
pattern = "/*"
custom_response = true
zone_id = ""
