# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"\x1d\n\x0cInputRequest\x12\r\n\x05input\x18\x01 \x01(\x0c\"B\n\x14ProcessImageResponse\x12\x17\n\x0fprocessed_image\x18\x01 \x01(\x0c\x12\x11\n\tmime_type\x18\x02 \x01(\t2B\n\tAIService\x12\x35\n\x07Process\x12\x10.ai.InputRequest\x1a\x18.ai.ProcessImageResponseB\x1bZ\x19\x63limbinsight/server/ai;aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031climbinsight/server/ai;ai'
  _globals['_INPUTREQUEST']._serialized_start=16
  _globals['_INPUTREQUEST']._serialized_end=45
  _globals['_PROCESSIMAGERESPONSE']._serialized_start=47
  _globals['_PROCESSIMAGERESPONSE']._serialized_end=113
  _globals['_AISERVICE']._serialized_start=115
  _globals['_AISERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
